#!env sh
#
# Testbed for figuring out the comments data
# Using YAML::Shell for dumping the Perl datastructure
# of the YAML file
#
# Using JSON::XS for converting from YAML to JSON

# Show one full discussion thread
# .../_c/$id
ysh -r < show_thread.yml

test $? = 0 && json_xs -f yaml -t json \
   < show_thread.yml \
   > show_thread.json


# List available threads
# .../_c/
ysh -r < list_threads.yml

test $? = 0 && json_xs -f yaml -t json \
   < list_threads.yml \
   > list_threads.json
